apiVersion: core.kubefed.io/v1beta1
kind: KubeFedConfig
metadata:
  name: kubefed
  namespace: kube-federation-system
spec:
  scope: Cluster
  controllerDuration:
    availableDelay: 20s
    unavailableDelay: 60s
  leaderElect:
    leaseDuration: 1500ms
    renewDeadline: 1000ms
    resourceLock: configmaps
    retryPeriod: 500ms
  featureGates:
  - name: PushReconciler
    configuration: "Enabled"
  - name: SchedulerPreferences
    configuration: "Enabled"
  - name: CrossClusterServiceDiscovery
    configuration: "Enabled"
  - name: FederatedIngress
    configuration: "Enabled"
  clusterHealthCheck:
    failureThreshold: 3
    period: 10s
    successThreshold: 1
    timeout: 3s
  syncController:
    adoptResources: Enabled
