apiVersion: types.kubefed.io/v1beta1
kind: FederatedServiceAccount
metadata:
  name: test-serviceaccount
  namespace: test-namespace
spec:
  template:
    automountServiceAccountToken: true
  placement:
    clusters:
    - name: cluster2
    - name: cluster1
